# Generated by Django 5.2.17 on 2026-09-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0001_initial"),
        ("locksmiths", "0007_locksmith_soter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=100)),
                ("report_id", models.CharField(max_length=100)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("on_route", "On route"),
                            ("arrived", "Arrived"),
                            ("parts_done", "Parts disposed"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("on_route_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("parts_done_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[("completed", "Completed"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locksmith",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_visits",
                        to="locksmiths.locksmith",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobVisitPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("before", "Before"), ("after", "After")],
                        max_length=10,
                    ),
                ),
                ("url", models.CharField(max_length=1000)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="locksmith_portal.jobvisit",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="jobvisit",
            constraint=models.UniqueConstraint(
                fields=("locksmith", "order_no"), name="one_job_visit_per_locksmith_job"
            ),
        ),
    ]
