# Generated by Django 5.2.17 on 2026-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0002_jobvisit_jobvisitphoto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvisit",
            name="access_method",
            field=models.CharField(
                blank=True,
                choices=[("picked", "Picked"), ("airbag", "Airbag")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="disclaimer_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wrong_parts", "Wrong parts"),
                    ("programmer_issue", "Programmer issue"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="failure_reattend_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self", "Reattend myself"),
                    ("different_locksmith", "Reattend with a different locksmith"),
                    ("none", "No reattend"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="failure_sku_needed",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="pick_used",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="jobvisitphoto",
            name="kind",
            field=models.CharField(
                choices=[
                    ("before", "Before"),
                    ("after", "After"),
                    ("door_frame", "Door frame"),
                    ("front_of_car", "Front of the car"),
                    ("door_lock", "Door with the lock"),
                    ("damage", "Damage"),
                    ("keys_supplied", "Keys supplied"),
                    ("client_key", "Client's key"),
                    ("ignition_on", "Ignition on"),
                    ("disclaimer_signature", "Disclaimer signature"),
                ],
                max_length=25,
            ),
        ),
    ]
