# Generated by Django 5.2.17 on 2026-09-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "locksmith_portal",
            "0003_jobvisit_access_method_jobvisit_disclaimer_signed_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disclaimer_text",
                    models.TextField(
                        default="We need to attempt to gain access with a rod and airbag. This is by placing an airbag in the door frame to provide enough gap to get a rod inside to attempt to pull the door handle. Although damage is rare, it might cause small bodywork damage that WGTK can't be held liable for."
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal settings",
                "verbose_name_plural": "Portal settings",
            },
        ),
        migrations.CreateModel(
            name="PortalPhotoPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_label",
                    models.CharField(
                        help_text='The Handl service label this applies to — must match exactly (e.g. "Gain access", "AKL", "Spare Key"). Use "Default" as the catch-all for any service without its own rows.',
                        max_length=50,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            (
                                "access_method",
                                "Access method (Gain access airbag step)",
                            ),
                            ("complete", "Finish job"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("before", "Before"),
                            ("after", "After"),
                            ("door_frame", "Door frame"),
                            ("front_of_car", "Front of the car"),
                            ("door_lock", "Door with the lock"),
                            ("damage", "Damage"),
                            ("keys_supplied", "Keys supplied"),
                            ("client_key", "Client's key"),
                            ("ignition_on", "Ignition on"),
                            ("disclaimer_signature", "Disclaimer signature"),
                        ],
                        help_text="Which photo evidence this is — matches up to the uploaded photo's kind.",
                        max_length=25,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Shown to the locksmith as the field label. Leave blank to use the photo kind's own label.",
                        max_length=100,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers show first, within the same service and step.",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to retire a prompt without deleting its history.",
                    ),
                ),
            ],
            options={
                "ordering": ["service_label", "step", "order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service_label", "step", "kind"),
                        name="one_photo_prompt_per_service_step_kind",
                    )
                ],
            },
        ),
    ]
