# Generated by Django 5.2.17 on 2026-09-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0005_seed_portal_photo_prompts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortalPhotoPrompt",
        ),
        migrations.DeleteModel(
            name="PortalSettings",
        ),
    ]
