# Generated by Django 5.2.17 on 2026-09-04 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_completion", "0009_completedjob_net_cost"),
        ("locksmith_portal", "0007_alter_jobvisitphoto_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvisit",
            name="failure_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="job_completion.failurecategory",
            ),
        ),
    ]
