# Generated by Django 5.2.17 on 2026-09-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0008_jobvisit_failure_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvisit",
            name="completion_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobvisitphoto",
            name="kind",
            field=models.CharField(
                choices=[
                    ("before", "Before"),
                    ("after", "After"),
                    ("door_frame", "Door frame"),
                    ("front_of_car", "Front of the car (with the reg plate visible)"),
                    ("door_lock", "Door with the lock"),
                    ("damage", "Damage"),
                    ("keys_supplied", "Keys supplied"),
                    ("client_key", "Client's key"),
                    ("ignition_on", "Ignition on"),
                    ("disclaimer_signature", "Disclaimer signature"),
                    ("completion_signature", "Completion sign-off signature"),
                ],
                max_length=25,
            ),
        ),
    ]
