# Generated by Django 5.2.17 on 2026-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0009_jobvisit_completion_signed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvisit",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("client_cancelled", "Client cancelled"),
                    ("office_pulled", "Office pulled the job"),
                    ("couldnt_attend", "Couldn't attend — traffic/weather"),
                    ("wrong_address", "Wrong address/details"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="customer_not_present_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="jobvisit",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
