# Generated by Django 5.2.17 on 2026-09-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0010_jobvisit_cancel_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvisit",
            name="arrival_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="arrival_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
