# Generated by Django 5.2.17 on 2026-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "locksmith_portal",
            "0011_jobvisit_arrival_latitude_jobvisit_arrival_longitude",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="portaldisposal",
            name="client_supplied",
            field=models.BooleanField(default=False),
        ),
    ]
