# Generated by Django 5.2.17 on 2026-09-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0012_portaldisposal_client_supplied"),
        ("locksmiths", "0007_locksmith_soter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeniorStaffContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=30)),
                ("active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Senior staff contact",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SafetyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("panic", "Panic button"), ("overdue", "Overdue job")],
                        max_length=20,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notified_contacts",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated names of who was alerted, for the record.",
                    ),
                ),
                (
                    "job_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_alerts",
                        to="locksmith_portal.jobvisit",
                    ),
                ),
                (
                    "locksmith",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_alerts",
                        to="locksmiths.locksmith",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
    ]
