# Generated by Django 5.2.17 on 2026-09-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0014_alter_jobvisitphoto_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvisit",
            name="further_work_details",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="further_work_required",
            field=models.BooleanField(default=False),
        ),
    ]
