# Generated by Django 5.2.17 on 2026-09-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0015_jobvisit_further_work_details_and_more"),
        ("locksmiths", "0010_alter_locksmith_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTimingSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=100)),
                ("report_id", models.CharField(max_length=100)),
                ("reg", models.CharField(blank=True, max_length=20)),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("vin", models.CharField(blank=True, max_length=50)),
                (
                    "travel_time",
                    models.DurationField(
                        blank=True,
                        help_text="on_route_at to arrived_at — how long the locksmith was travelling to this job.",
                        null=True,
                    ),
                ),
                (
                    "job_time",
                    models.DurationField(
                        blank=True,
                        help_text="arrived_at to completed_at — how long the locksmith was on site for this job.",
                        null=True,
                    ),
                ),
                ("skus_used", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locksmith",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_timing_summaries",
                        to="locksmiths.locksmith",
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timing_summary",
                        to="locksmith_portal.jobvisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job timing summary",
                "verbose_name_plural": "Job timing summaries",
                "ordering": ["-created_at"],
            },
        ),
    ]
