# Generated by Django 5.2.17 on 2026-09-10 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0016_jobtimingsummary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="portaldisposal",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PortalDisposalEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("edit", "Edited"),
                            ("late_add", "Added after job completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("old_part_code", models.CharField(blank=True, max_length=64)),
                ("old_part_name", models.CharField(blank=True, max_length=200)),
                ("old_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("new_part_code", models.CharField(blank=True, max_length=64)),
                ("new_part_name", models.CharField(blank=True, max_length=200)),
                ("new_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("handl_note_error", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edits",
                        to="locksmith_portal.portaldisposal",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
    ]
