# Generated by Django 5.2.17 on 2026-09-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0017_portaldisposal_needs_review_portaldisposaledit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobvisitphoto",
            name="kind",
            field=models.CharField(
                choices=[
                    ("before", "Before"),
                    ("after", "After"),
                    ("door_frame", "Door frame"),
                    ("door_open", "Door open"),
                    ("key_in_hand", "Key in hand"),
                    ("front_of_car", "Front of the car (with the reg plate visible)"),
                    ("door_lock", "Door with the lock"),
                    ("damage", "Damage"),
                    ("blade_in_door", "Blade turned in the door"),
                    ("blade_in_ignition", "Blade turned in the ignition"),
                    ("keys_supplied", "Keys supplied"),
                    ("client_key", "New key with the client's key"),
                    ("ignition_on", "Ignition on"),
                    ("mileage", "Mileage"),
                    ("disclaimer_signature", "Disclaimer signature"),
                    ("completion_signature", "Completion sign-off signature"),
                ],
                max_length=25,
            ),
        ),
    ]
