# Generated by Django 5.2.17 on 2026-09-10 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0018_alter_jobvisitphoto_kind"),
        ("locksmiths", "0010_alter_locksmith_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaultyPartReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=100)),
                ("report_id", models.CharField(max_length=100)),
                ("part_code", models.CharField(max_length=64)),
                ("part_name", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField()),
                ("vin", models.CharField(blank=True, max_length=50)),
                ("reg", models.CharField(blank=True, max_length=20)),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("spare_key", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("handl_synced", models.BooleanField(default=False)),
                ("handl_error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locksmith",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faulty_part_reports",
                        to="locksmiths.locksmith",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
