# Generated by Django 5.2.17 on 2026-09-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0019_faultypartreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtimingsummary",
            name="year",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
