# Generated by Django 5.2.17 on 2026-09-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0020_jobtimingsummary_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvisit",
            name="key_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jobvisit",
            name="access_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("picked", "Picked"),
                    ("airbag", "Airbag"),
                    ("key_code", "Key code supplied"),
                ],
                max_length=20,
            ),
        ),
    ]
