# Generated by Django 5.2.17 on 2026-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0020_jobtimingsummary_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobvisit",
            name="access_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("picked", "Picked"),
                    ("airbag", "Airbag"),
                    ("key_code", "Key code supplied"),
                    ("dealer_key", "Dealer-supplied key (pre-cut)"),
                ],
                max_length=20,
            ),
        ),
    ]
