# Generated by Django 5.2.17 on 2026-09-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0021_alter_jobvisit_access_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(unique=True)),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
