# Generated by Django 5.2.17 on 2026-09-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0023_seed_pay_periods"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvisit",
            name="make",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="reg",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="jobvisit",
            name="year",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
