# Generated by Django 5.2.17 on 2026-09-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "locksmith_portal",
            "0024_jobvisit_make_jobvisit_model_name_jobvisit_reg_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobvisit",
            name="access_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("picked", "Picked"),
                    ("airbag", "Airbag"),
                    ("key_code", "Key code supplied"),
                    ("dealer_key", "Dealer-supplied key (pre-cut)"),
                    (
                        "already_open",
                        "Vehicle already open — customer had a working key",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
