# Generated by Django 5.2.17 on 2026-09-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0026_alter_jobvisitphoto_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobVisitVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_claim_id", models.CharField(max_length=50)),
                ("reg", models.CharField(blank=True, max_length=20)),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("vin", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="locksmith_portal.jobvisit",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="faultypartreport",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faulty_part_reports",
                to="locksmith_portal.jobvisitvehicle",
            ),
        ),
        migrations.AddField(
            model_name="jobvisitphoto",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="locksmith_portal.jobvisitvehicle",
            ),
        ),
        migrations.AddField(
            model_name="portaldisposal",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disposals",
                to="locksmith_portal.jobvisitvehicle",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobvisitvehicle",
            constraint=models.UniqueConstraint(
                fields=("visit", "key_claim_id"), name="one_vehicle_row_per_key_claim"
            ),
        ),
    ]
