# Generated by Django 5.2.17 on 2026-09-18 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_completion", "0010_completedjob_notes_sufficient"),
        ("locksmith_portal", "0027_jobvisitvehicle_faultypartreport_vehicle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvisitphoto",
            name="signed_for_vehicles",
            field=models.ManyToManyField(
                blank=True,
                related_name="covering_signatures",
                to="locksmith_portal.jobvisitvehicle",
            ),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="access_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("picked", "Picked"),
                    ("airbag", "Airbag"),
                    ("key_code", "Key code supplied"),
                    ("dealer_key", "Dealer-supplied key (pre-cut)"),
                    (
                        "already_open",
                        "Vehicle already open — customer had a working key",
                    ),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="before_done_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="customer_not_present_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="disclaimer_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="failure_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="job_completion.failurecategory",
            ),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="failure_reattend_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self", "Reattend myself"),
                    ("different_locksmith", "Reattend with a different locksmith"),
                    ("none", "No reattend"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="failure_sku_needed",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="further_work_details",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="further_work_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="parts_done_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="pick_used",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="signed_off_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="spare_key",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobvisitvehicle",
            name="stage",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("before_done", "Before photos done"),
                    ("parts_done", "Parts disposed"),
                    ("done", "Done"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
