# Generated by Django 5.2.17 on 2026-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmith_portal", "0028_jobvisitphoto_signed_for_vehicles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobvisit",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("client_cancelled", "Client cancelled"),
                    ("client_not_answering", "Client not answering — didn't attend"),
                    ("office_pulled", "Office pulled the job"),
                    ("couldnt_attend", "Couldn't attend — traffic/weather"),
                    ("wrong_address", "Wrong address/details"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
