# Generated by Django 5.2.17 on 2026-09-01 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locksmiths", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VarianceThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_threshold",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Flag when |actual - expected| exceeds this many units.",
                    ),
                ),
                (
                    "pct_threshold",
                    models.DecimalField(
                        decimal_places=1,
                        default=10.0,
                        help_text="Flag when the variance exceeds this percentage of expected qty.",
                        max_digits=5,
                    ),
                ),
                (
                    "value_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=25.0,
                        help_text="Flag when the £ impact of the variance exceeds this amount.",
                        max_digits=8,
                    ),
                ),
                (
                    "repeat_offender_occurrences",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of flagged weeks that counts as a repeat offender...",
                    ),
                ),
                (
                    "repeat_offender_window_weeks",
                    models.PositiveIntegerField(
                        default=4, help_text="...within this many most recent weeks."
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Variance threshold configuration",
                "verbose_name_plural": "Variance threshold configuration",
            },
        ),
        migrations.CreateModel(
            name="StockCheckSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                        ]
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "locksmith",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_check_schedule",
                        to="locksmiths.locksmith",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyStockCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_starting", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                            ("awaiting_entry", "Awaiting count entry"),
                            ("completed", "Completed"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "locksmith",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_checks",
                        to="locksmiths.locksmith",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_starting"],
                "unique_together": {("locksmith", "week_starting")},
            },
        ),
        migrations.CreateModel(
            name="StockCheckItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_code", models.CharField(max_length=64)),
                ("part_name", models.CharField(max_length=200)),
                ("expected_qty", models.PositiveIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("actual_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("entered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weekly_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stock_accuracy.weeklystockcheck",
                    ),
                ),
            ],
            options={
                "ordering": ["part_code"],
            },
        ),
    ]
