# Generated by Django 5.2.17 on 2026-09-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_accuracy", "0002_emailsettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailSettings",
        ),
        migrations.RemoveField(
            model_name="weeklystockcheck",
            name="sent_at",
        ),
        migrations.AlterField(
            model_name="weeklystockcheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("generated", "Generated"),
                    ("awaiting_entry", "Awaiting count entry"),
                    ("completed", "Completed"),
                ],
                default="generated",
                max_length=20,
            ),
        ),
    ]
