# Generated by Django 5.2.17 on 2026-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stock_accuracy",
            "0003_delete_emailsettings_remove_weeklystockcheck_sent_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualStockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_code", models.CharField(max_length=64, unique=True)),
                (
                    "part_name",
                    models.CharField(
                        blank=True,
                        help_text="For reference only — not matched on.",
                        max_length=200,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Virtual stock item (excluded from stock checks)",
                "verbose_name_plural": "Virtual stock items (excluded from stock checks)",
                "ordering": ["part_code"],
            },
        ),
    ]
