# Generated by Django 5.2.17 on 2026-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_accuracy", "0005_seed_3d_job_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartUnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_code", models.CharField(max_length=64, unique=True)),
                (
                    "part_name",
                    models.CharField(
                        blank=True,
                        help_text="For reference only — not matched on.",
                        max_length=200,
                    ),
                ),
                (
                    "units_per_pack",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Handl's expected_qty for this SKU is in packs of this size — multiplied by this before comparing to the locksmith's individual-unit count.",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Part unit conversion (pack size mismatch)",
                "verbose_name_plural": "Part unit conversions (pack size mismatches)",
                "ordering": ["part_code"],
            },
        ),
    ]
