# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_accuracy", "0007_seed_vxrp2_pack_conversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcheckitem",
            name="handl_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stockcheckitem",
            name="handl_synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weeklystockcheck",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklystockcheck",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
