# Generated by Django 5.2.17 on 2026-09-01 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locksmiths", "0003_optimodriverid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Failure categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SLATarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=100, unique=True)),
                ("target_minutes", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["service_type"],
            },
        ),
        migrations.CreateModel(
            name="CompletedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=100, unique=True)),
                (
                    "report_id",
                    models.CharField(
                        help_text="Handl ReportID, parsed from order_no.",
                        max_length=100,
                    ),
                ),
                ("job_date", models.DateField()),
                (
                    "driver_serial",
                    models.CharField(
                        blank=True,
                        help_text="Raw Optimo driverSerial — kept even when it couldn't be matched to a locksmith, so unmatched drivers are visible.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("distance_metres", models.FloatField(default=0)),
                ("travel_time_seconds", models.PositiveIntegerField(default=0)),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("service_type", models.CharField(blank=True, max_length=100)),
                (
                    "failure_note",
                    models.TextField(
                        blank=True,
                        help_text="Driver's free-text note from Optimo, if any.",
                    ),
                ),
                ("categorized_at", models.DateTimeField(blank=True, null=True)),
                ("pulled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "categorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locksmith",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_jobs",
                        to="locksmiths.locksmith",
                    ),
                ),
                (
                    "failure_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="job_completion.failurecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-job_date", "order_no"],
            },
        ),
    ]
