# Generated by Django 5.2.17 on 2026-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_completion", "0002_rename_failure_note_completedjob_completion_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedjob",
            name="vin",
            field=models.CharField(blank=True, max_length=32, verbose_name="VIN"),
        ),
        migrations.AlterField(
            model_name="completedjob",
            name="completion_note",
            field=models.TextField(
                blank=True,
                help_text="Driver's free-text completion note from Optimo — written for any job, not just failures (e.g. a summary of work done).",
            ),
        ),
    ]
