# Generated by Django 5.2.17 on 2026-09-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_completion", "0003_completedjob_vin_alter_completedjob_completion_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedjob",
            name="disposed_skus",
            field=models.CharField(
                blank=True,
                help_text="SKUs of parts disposed against this job (comma-separated, most recent first).",
                max_length=255,
            ),
        ),
    ]
