# Generated by Django 5.2.17 on 2026-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_completion", "0004_completedjob_disposed_skus"),
    ]

    operations = [
        migrations.AddField(
            model_name="failurecategory",
            name="master_reason",
            field=models.CharField(
                choices=[
                    ("wgtk_office", "WGTK Office"),
                    ("client", "Client"),
                    ("supplier", "Supplier"),
                    ("wgtk_locksmith", "WGTK Locksmith"),
                    ("none", "None"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
