# Generated by Django 5.2.17 on 2026-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_completion", "0005_failurecategory_master_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedjob",
            name="loss_type",
            field=models.CharField(
                blank=True,
                help_text="Handl LossEvent, e.g. Lost Keys/Lockout.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="completedjob",
            name="supplied_service",
            field=models.CharField(
                blank=True,
                help_text="Service the locksmith actually supplied, e.g. Non-Destructive Entry.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="completedjob",
            name="service_type",
            field=models.CharField(
                blank=True,
                help_text="Handl KeyType, e.g. Car/Van/Motorbike.",
                max_length=100,
            ),
        ),
    ]
