# Generated by Django 5.2.17 on 2026-09-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_completion", "0007_rename_service_type_slatarget_loss_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slatarget",
            options={"ordering": ["loss_type"]},
        ),
    ]
