# Generated by Django 5.2.17 on 2026-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_completion", "0008_alter_slatarget_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedjob",
            name="net_cost",
            field=models.FloatField(
                blank=True,
                help_text="Handl's net cost for the job (Policy_Financial.NetCost) — what the client was charged, excl. VAT; the 'selling price' side of the parts-cost margin calc.",
                null=True,
            ),
        ),
    ]
