# Generated by Django 5.2.17 on 2026-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_completion", "0009_completedjob_net_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedjob",
            name="notes_sufficient",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Office's QC judgement, made alongside categorizing a failure, on whether the locksmith's completion_note was good enough — null until then, not a default of False. Feeds a per-locksmith QC metric rather than blocking categorization.",
                null=True,
            ),
        ),
    ]
