# Generated by Django 5.2.17 on 2026-09-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locksmith",
            name="handl_engineer_id",
        ),
        migrations.CreateModel(
            name="SoterLocksmithId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "soter_locksmith_id",
                    models.CharField(
                        help_text="Lookup_Locksmiths.ID in Soter, e.g. '1163'.",
                        max_length=64,
                    ),
                ),
                (
                    "locksmith",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soter_ids",
                        to="locksmiths.locksmith",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soter locksmith ID",
                "unique_together": {("locksmith", "soter_locksmith_id")},
            },
        ),
    ]
