# Generated by Django 5.2.17 on 2026-09-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0002_remove_locksmith_handl_engineer_id_soterlocksmithid"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptimoDriverId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "optimo_driver_serial",
                    models.CharField(
                        help_text="Optimo driverSerial, e.g. '011'.", max_length=64
                    ),
                ),
                (
                    "locksmith",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimo_driver_ids",
                        to="locksmiths.locksmith",
                    ),
                ),
            ],
            options={
                "verbose_name": "Optimo driver ID",
                "unique_together": {("locksmith", "optimo_driver_serial")},
            },
        ),
    ]
