# Generated by Django 5.2.17 on 2026-09-03 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0003_optimodriverid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="locksmith",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked automatically the first time this locksmith signs in with a Microsoft account matching their email — grants access to the self-service portal at /locksmith/ instead of office/admin access.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locksmith_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
