# Generated by Django 5.2.17 on 2026-09-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0004_locksmith_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="locksmith",
            name="sees_all_jobs_for_testing",
            field=models.BooleanField(
                default=False,
                help_text="Portal shows every job scheduled today instead of only jobs assigned to this locksmith's own Optimo driver ID(s) — for an office/admin test account exercising the portal, never a real field locksmith.",
            ),
        ),
    ]
