# Generated by Django 5.2.17 on 2026-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0005_locksmith_sees_all_jobs_for_testing"),
    ]

    operations = [
        migrations.AddField(
            model_name="soterlocksmithid",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[("V", "Van"), ("A", "Admin")],
                help_text="Parsed from the '(V)'/'(A)' suffix on the Soter name, when present — see Locksmith.van_soter_id.",
                max_length=1,
            ),
        ),
    ]
