# Generated by Django 5.2.17 on 2026-09-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0006_soterlocksmithid_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="locksmith",
            name="soter_user_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="This locksmith's own personal Soter login id (wiki.LocksmithLogin.UserId, matched by name during sync) — used to attribute portal disposals to them individually, matching how Soter already attributes real disposals (not a shared account).",
                null=True,
            ),
        ),
    ]
