# Generated by Django 5.2.17 on 2026-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0007_locksmith_soter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="locksmith",
            name="preferred_navigation_app",
            field=models.CharField(
                blank=True,
                choices=[("maps", "Google Maps"), ("waze", "Waze")],
                help_text="Which app the portal's \"Mark on route\" step opens automatically for turn-by-turn navigation — set the first time this locksmith picks Maps or Waze there, so they aren't asked again on every job. Clear this to have them asked again next time.",
                max_length=10,
            ),
        ),
    ]
