# Generated by Django 5.2.17 on 2026-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0008_locksmith_preferred_navigation_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="locksmith",
            name="office_access",
            field=models.BooleanField(
                default=False,
                help_text="Also gives this locksmith the office/admin side of the tool (Job Completion, Panel Spend, etc.) on top of their normal self-service portal access at /locksmith/ — for the rare locksmith who also does office work. See apps.accounts.middleware.RestrictLocksmithsToPortalMiddleware.",
            ),
        ),
    ]
