# Generated by Django 5.2.17 on 2026-09-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0010_alter_locksmith_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="locksmith",
            name="home_postcode",
            field=models.CharField(
                blank=True,
                help_text="This locksmith's home/base postcode — there's no live GPS tracking of where a locksmith actually is, so this is used as a stand-in \"where they're based\" for Logs Engine's nearest-locksmith distance lookup (Area: office job lookup). Office-entered, not synced from anywhere.",
                max_length=16,
            ),
        ),
    ]
