# Generated by Django 5.2.17 on 2026-09-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locksmiths", "0011_locksmith_home_postcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="locksmith",
            name="home_latitude",
            field=models.FloatField(
                blank=True,
                help_text='This locksmith\'s home/base location, more precise than home_postcode above — sourced from Optimo\'s own "driver starting location" (see "Sync from employee locations" in Locksmiths admin, a file upload since Optimo has no live API for this), and preferred over home_postcode by Logs Engine\'s nearest-locksmith distance lookup whenever both are set.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="locksmith",
            name="home_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="locksmith",
            name="home_postcode",
            field=models.CharField(
                blank=True,
                help_text="This locksmith's home/base postcode — there's no live GPS tracking of where a locksmith actually is, so this is used as a stand-in \"where they're based\" for Logs Engine's nearest-locksmith distance lookup (Area: office job lookup), when home_latitude/home_longitude below aren't set. Office-entered, not synced from anywhere.",
                max_length=16,
            ),
        ),
    ]
